name: Build

on:
  push:
  pull_request:
  workflow_dispatch:

jobs:
  calculate-version:
    name: Calculate Version
    runs-on: ubuntu-latest
    outputs:
      semVer: ${{ steps.gitversion.outputs.fullSemVer }}
    steps:
      - uses: actions/checkout@v3
        name: Checkout code
        with:
          fetch-depth: 0

      - uses: gittools/actions/gitversion/setup@v0.9.7
        name: Install GitVersion
        with:
          versionSpec: '5.x'

      - uses: gittools/actions/gitversion/execute@v0.9.7
        name: Determine Version
        id: gitversion
        with:
          useConfigFile: true
          configFilePath: gitversion.yml

  build:
    name: Build
    runs-on: ubuntu-latest
    needs: calculate-version
    steps:
      - uses: actions/checkout@v3
        name: Checkout code

      - name: Docker login
        run: echo ${{ secrets.GITHUB_TOKEN }} | docker login ghcr.io -u rbjoergensen --password-stdin

      - name: Docker build
        run: docker build . --tag ghcr.io/rbjoergensen/api-callofthevoid:${{ needs.calculate-version.outputs.semVer }}

      - name: Docker push
        run: docker push ghcr.io/rbjoergensen/api-callofthevoid:${{ needs.calculate-version.outputs.semVer }}